name: Ethan Swan
markdown: kramdown
permalink: /feed/:year/:month/:day/:title
theme: alembic-jekyll-theme

excerpt_separator: <!--more-->

exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- vendor

collections:
  coffee_shops:
    output: true
