name: Continuous Integration

on: push

jobs:
  test:
    name: Test
    container:
      image: netlify/build:xenial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: lets see
        run: |
          ls && pwd
